version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        links:
            - php-fpm
        volumes:
            - ./:/var/www/html

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/html
        links:
            - mysql

    mysql:
        container_name: mysql
        image: mysql:5.7
        tty: true
        platform: linux/amd64
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api_tickets
            MYSQL_USER: user
            MYSQL_PASSWORD: zagirok123





